---
title: "MAIN"
---

```{r include=FALSE, message=FALSE}
source('auxiliares/comprobar_mapas.R')

```

## Graficando un mapa

```{r fig, fig.height = 8, fig.width = 8, fig.align = "center"}

library(sf)
library(ggplot2)
library(ggrepel)
library(dplyr)
library(tidyverse)

n_lng <- c(
-80, # OD AMAZONAS
-82, # OD ANCASH
-73.5, # OD APURIMAC
-71, # OD AREQUIPA
-78, # OD AYACUCHO
-84, # OD CAJAMARCA
-68, # OD CUSCO
-80, # OD HUANCAVELICA
-72, # OD HUANUCO
-76, # OD ICA
-79, # OD JUNIN
-83, # OD LA LIBERTAD
-84, # OD LAMBAYEQUE
-70, # OD LORETO
-67, # OD MADRE DE DIOS
-67, # OD MOQUEGUA
-81, # OD PASCO
-84, # OD PIURA
-66.5, # OD PUNO
-70, # OD SAN MARTIN
-68, # OD TACNA
-82, # OD TUMBES
-69, # OD UCAYALI
-80, # OD VRAEM
-82, # OE CHIMBOTE
-76, # OE CORACORA
-66, # OE COTABAMBAS
-67, # OE ESPINAR
-69, # OE LA CONVENCION
-70, # OE PICHANAKI
-81 # OFICINA CENTRAL
)

n_lat <- c(
-2, # OD AMAZONAS
-9.5, # OD ANCASH
-18, # OD APURIMAC
-19, # OD AREQUIPA
-14, # OD AYACUCHO
-7, # OD CAJAMARCA
-11.5, # OD CUSCO
-13, # OD HUANCAVELICA
-8, # OD HUANUCO
-16, # OD ICA
-11, # OD JUNIN
-7.8, # OD LA LIBERTAD
-5.5, # OD LAMBAYEQUE
-1.5, # OD LORETO
-10, # OD MADRE DE DIOS
-17, # OD MOQUEGUA
-10.5, # OD PASCO
-4, # OD PIURA
-15, # OD PUNO
-6, # OD SAN MARTIN
-18, # OD TACNA
-2.5, # OD TUMBES
-8, # OD UCAYALI
-12.5, # OD VRAEM
-9, # OE CHIMBOTE
-17, # OE CORACORA
-13.5, # OE COTABAMBAS
-14.5, # OE ESPINAR
-9, # OE LA CONVENCION
-1, # OE PICHANAKI
-11.5 # OFICINA CENTRAL
)

mapa <- mapas$od
mapa <- mapa[order(mapa$ABREV_OD),]

mapa_c <- st_centroid(mapa) 
mapa_c <- mapa_c %>% 
  mutate(
    lng = unlist(map(mapa_c$geometry,1)),
    lat = unlist(map(mapa_c$geometry,2))
    )

mapa_c <- mapa_c %>% 
  mutate(
    n_lng = n_lng,
    n_lat = n_lat,
    nudge_lng = n_lng - mapa_c$lng,
    nudge_lat = n_lat - mapa_c$lat
      )

graph <- ggplot(data=mapa, aes())+
  geom_sf(color="grey", fill="white")+
  ggtitle('MAPA DEL PERÚ - DEMARCACIÓN TERRITORIAL POR ODE')+
  theme_void()+
  theme(
    plot.title = element_text(hjust = 0.5)
    )+
  geom_sf(data = mapas$lago_titicaca, color='black', fill='lightblue')+
  geom_sf(data = mapa_c, color = 'red')+
  geom_text_repel(
    data= mapa_c, aes(x = lng, y = lat, label=ABREV_OD),
    color='black',
    fontface = "bold", 
    size = 3,
    #box.padding = 0.5,
    #force = 1,
    #force_pull = 1,
    nudge_x = mapa_c$nudge_lng,
    nudge_y = mapa_c$nudge_lat,
    direction = "both",
    segment.curvature = -1e-20,
    segment.ncp = 5,
    segment.angle = 30
    )+
  expand_limits(x = c(-85,-66), y = c(0,-19))
graph

```




























