---
title: "RR Book"
---

# Cuaderno de trabajo con Datos de RR 

## Librerías

```{r}
library(dplyr)
library(sf)
library(Hmisc)
library(stringr)
```


## Datos de alertas

### Importar datos de Reporta Residuos

```{r}

rr <- read.csv("rr.csv", header = TRUE)
rr

```

### Generar archivo de puntos de Reporta Residuos

```{r}

# Geometry

rr_longitud <- rr$LONGITUD
rr_latitud <- rr$LATITUD

rr_coords <- data.frame(cbind(rr_longitud, rr_latitud))
rr_geometry <- st_sfc()

for(i in 1:nrow(rr_coords)){
  a <- rr_coords$rr_longitud[i]
  b <- rr_coords$rr_latitud[i]
  P <- st_point(c(a, b))
  rr_geometry[[i]] <- P
}

# Atributos adicionales

rr_ID_GEN <- rr$ID_GEN
rr_OBJECTID <- rr$OBJECTID
rr_DEPARTAMENTO <- rr$DEPARTAMENTO
rr_PROVINCIA <- rr$PROVINCIA
rr_DISTRITO <- rr$DISTRITO
rr_FECHA <- rr$FECHA_TOMA
rr_HORA <- rr$HORA_FOTO
rr_ESTADO <- rr$ESTADO_ALERTA

rr_atributos <- data.frame(
  rr_ID_GEN,
  rr_OBJECTID,
  rr_DEPARTAMENTO,
  rr_PROVINCIA,
  rr_DISTRITO,
  rr_FECHA,
  rr_HORA,
  rr_ESTADO
)

rr_atributos <- mutate(
  rr_atributos,
  rr_UBIGEO = paste(rr_atributos$rr_DEPARTAMENTO,"-",rr_atributos$rr_PROVINCIA,"-",rr_atributos$rr_DISTRITO)
)

# Colección

rr_sfp <- st_sf(rr_atributos, geometry = rr_geometry)
st_crs(rr_sfp) <- "WGS 84"
rr_sfp

```

## Mapa del Perú

```{r}

md <- st_read("peru/distritos/DISTRITOS.shp")
md_data <- select(as.data.frame(md), CCDD:NOMBDIST)
md_data <- mutate(
  md_data,
  md_ubigeo = paste(md_data$NOMBDEP,"-",md_data$NOMBPROV,"-",md_data$NOMBDIST)
)
md_geom <- st_geometry(md)
md <- st_sf(md_data, geometry = md_geom)
md

```

## Mapa del Perú con puntos del Reporta Residuos

```{r}

plot(st_geometry(md),axes=T)
plot(st_geometry(rr_sfp), add=TRUE, col="red")

```
## Por distrito

```{r}


md_ubigeo <- md$md_ubigeo
rr_UBIGEO <- rr_sfp$rr_UBIGEO
rr_UBIGEO <- unique(rr_UBIGEO)

a <- length(rr_UBIGEO)
b <- length(rr_UBIGEO %in% md_ubigeo)
c <- length(intersect(md_ubigeo, rr_UBIGEO))
d <- length(setdiff(rr_UBIGEO, md_ubigeo))
e <- length(setdiff(md_ubigeo, rr_UBIGEO))
f <- c + e

g= c(a, b, c, d, e, f)
print(g)




```



```{r}

ubigeo <- intersect(md_ubigeo, rr_UBIGEO)
sort(ubigeo)
ubigeo

for(value in ubigeo){
  puntos <- filter(
    rr_sfp,
    rr_UBIGEO== value
  )
  
  plot(st_geometry(md[md_ubigeo==value,]), axes=T, main=value, cex.axis=0.5)
  plot(st_geometry(puntos), add = TRUE,col="red", fill="red")
}

```








```{r}

for(value in ubigeo){
    
  puntos <- filter(
    rr_sfp,
    rr_UBIGEO== value
  )%>%
    st_set_crs(4326) %>% st_transform(crs=32736)

    graph <- ggplot(data=md[md_ubigeo==value,])+
      geom_sf(color="white", fill="lightblue")+
      ggtitle(value)
    
    graph <- graph+
      geom_sf(data = puntos, color="red", fill="red", shape=2)

    print(graph)
}

```



















