---
title: "Notas 3"
---

```{r}
library(sf)
library(dplyr)
library(Hmisc)
```


```{r}
mx <- st_read("peru/distritos/DISTRITOS.shp")
mx

```


```{r}
mx_data <- select(as.data.frame(mx), CCDD:NOMBDIST)
mx_geom <- st_geometry(mx)
mx <- st_sf(mx_data, geometry = mx_geom)

```


```{r}
png(
  "mapaperu.png",
  width = 5000,
  height = 5000,
  res = 256
  )
plot(mx_geom, border="black", col="lightblue", axes=T, cex.axis=1)

```

```{r}
mx_data2 <- mutate(
  mx_data,
  ubigeo = paste(mx_data$NOMBDEP,"-",mx_data$NOMBPROV,"-",mx_data$NOMBDIST)
  )
mx_data2

```



```{r}
ubigeo <- mx_data2$ubigeo

for(value in ubigeo){
  plot(st_geometry(mx[ubigeo==value,]), border="black", col="lightgreen", axes=T, main=value, cex.axis=0.5)
  minor.tick(nx=10, ny=10, tick.ratio=0.5)
}
```
```{r}
for(value in ubigeo){
graph <- ggplot(data=mx[ubigeo==value,])+
  geom_sf(color="black", fill="greenyellow")+
  ggtitle(value)+
  annotation_scale()+
  annotation_north_arrow(location='tl', height = unit(0.8, "cm"), width= unit(0.8, "cm"))
print(graph)
}
```


```{r}
length(ubigeo)
```



















